### ISSUE TITLE
SNARK for ECDSA

### ISSUE THREAD

**Issue by alexander-camuto** [retrieval-markets-lab/das-quarry#15]
- We should be able to verify that a hashed-message was correctly signed by a given public key.

**Comment by tchardin** [comment]
@alexander-camuto why pick ECDSA btw, could have picked Secpk or BLS no?

**Comment by alexander-camuto** [comment]
Secpk is just a curve and can be combined with ecdsa, which is a signing algo :) the example in the PR actually uses secp256. BLS, like ECDSA, is a signing scheme. 

As to why ECDSA vs BLS. BLS can be more expensive to verify, and if we're in compute constrained environments, might be best to start with ECDSA. 

However things get dicier when we start aggregating. BLS has nicer properties when aggregating (in terms of sig size etc...) so might be good to explore then as well.
